name: Update Uptime Badge

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Day.js
        run: npm install dayjs

      - name: Generate Uptime
        run: node uptime.js

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add uptime.svg
          git commit -m "⏱️ Update uptime" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://Sacrafex:${GH_PAT}@github.com/Sacrafex/Sacrafex.git HEAD:main
